# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 200

# gazebo_ros_control/pid_gains:  # add this will remove the red error of pid, but the gazebo won't work with moveit
#   joint1: {p: 0.35,  d: 0, i: 0, i_clamp: 0}
#   joint2: {p: 0.35,  d: 0, i: 0, i_clamp: 0}
#   joint3: {p: 0.35,  d: 0, i: 0, i_clamp: 0}
#   joint4: {p: 0.35,  d: 0, i: 0, i_clamp: 0}
#   joint5: {p: 0.35,  d: 0, i: 0, i_clamp: 0}
#   joint6: {p: 0.35,  d: 0, i: 0, i_clamp: 0}
  # joint_gripper10: {p: -0.000001,  d: -0.000002, i: 0.0, i_clamp: 0}
  # joint_gripper20: {p: -0.000001,  d: -0.000002, i: 0.0, i_clamp: 0}
  # joint_gripper11: {p: -0.000001,  d: -0.000002, i: 0.0, i_clamp: 0}
  # joint_gripper21: {p: -0.000001,  d: -0.000002, i: 0.0, i_clamp: 0}

  /gazebo_ros_control:
    pid_gains:
      fl_steering_wheel:
        p: 50
        i: 1
        d: 0.01
      fr_steering_wheel:
        p: 50
        i: 1
        d: 0.01
      rl_steering_wheel:
        p: 50
        i: 1
        d: 0.01
      rr_steering_wheel:
        p: 50
        i: 1
        d: 0.01
      fl_wheel: #front_left_wheel
        p: 10.0
        i: 1
        d: 0.0
      fr_wheel: #front_right_wheel
        p: 10.0
        i: 1
        d: 0.0
      rl_wheel: #rear_left_wheel
        p: 10.0
        i: 1
        d: 0.0
      rr_wheel: #rear_right_wheel
        p: 10.0
        i: 1
        d: 0.0