# robot_group_position_controller:
#   type: position_controllers/JointGroupPositionController
#   joints: &robot_joints
#     - joint1
#     - joint2
#     - joint3
#     - joint4
#     - joint5
#     - joint6
#     - endright
#     - endleft

arm_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints: &arm_joints
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  gains:
    joint1: {p: 100, d: 1, i: 1, i_clamp: 1}
    joint2: {p: 100, d: 1, i: 1, i_clamp: 1}
    joint3: {p: 100, d: 1, i: 1, i_clamp: 1}
    joint4: {p: 100, d: 1, i: 1, i_clamp: 1}
    joint5: {p: 100, d: 1, i: 1, i_clamp: 1}
    joint6: {p: 100, d: 1, i: 1, i_clamp: 1}
  state_publish_rate: 200
  action_monitor_rate: 10

gripper_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints: &gripper_joints
    - endleft
    - endright
  gains:
    endright: {p: 100, d: 1, i: 1, i_clamp: 1}
    endleft: {p: 100, d: 1, i: 1, i_clamp: 1}
  state_publish_rate: 200
  action_monitor_rate: 10

# arm_position_controller:
#   type: position_controllers/JointTrajectoryController
#   joints: *arm_joints
#   gains:
#     joint1: {p: 100, d: 1, i: 1, i_clamp: 1}
#     joint2: {p: 100, d: 1, i: 1, i_clamp: 1}
#     joint3: {p: 100, d: 1, i: 1, i_clamp: 1}
#     joint4: {p: 100, d: 1, i: 1, i_clamp: 1}
#     joint5: {p: 100, d: 1, i: 1, i_clamp: 1}
#     joint6: {p: 100, d: 1, i: 1, i_clamp: 1}
#   constraints:
#     # goal_time: 0.6
#     stopped_velocity_tolerance: 0.0
#     joint1: {trajectory: 0.1, goal: 0.1}
#     joint2: {trajectory: 0.1, goal: 0.1}
#     joint3: {trajectory: 0.1, goal: 0.1}
#     joint4: {trajectory: 0.1, goal: 0.1}
#     joint5: {trajectory: 0.1, goal: 0.1}
#     joint6: {trajectory: 0.1, goal: 0.1}
#   # stop_trajectory_duration: 0.5
#   state_publish_rate: *loop_hz
#   action_monitor_rate: 10

# gripper_position_controller:
#   type: position_controllers/JointTrajectoryController
#   joints: *gripper_joints
#   gains:
#     endright: {p: 100, d: 1, i: 1, i_clamp: 1}
#     endleft: {p: 100, d: 1, i: 1, i_clamp: 1}
#   state_publish_rate: *loop_hz
#   action_monitor_rate: 10

# # Joint controllers' config
# joint1_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint1
#   pid: {p: 100, i: 1, d: 1}

# joint2_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint2
#   pid: {p: 100, i: 1, d: 1}

# joint3_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint3
#   pid: {p: 100, i: 1, d: 1}

# joint4_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint4
#   pid: {p: 100, i: 1, d: 1}

# joint5_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint5
#   pid: {p: 100, i: 1, d: 1}

# joint6_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint6
#   pid: {p: 100, i: 1, d: 1}

# joint_gripper11_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint_gripper11
#   pid: {p: 100, i: 1, d: 1}

# joint_gripper10_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint_gripper10
#   pid: {p: 100, i: 1, d: 1}

# joint_gripper21_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint_gripper21
#   pid: {p: 100, i: 1, d: 1}

# joint_gripper20_position_controller:
#   type: position_controllers/JointPositionController
#   joint: joint_gripper20
#   pid: {p: 100, i: 1, d: 1} 