rm2_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - wheel_joint1
    - wheel_joint2
    - wheel_joint3
    - wheel_joint4
    - steer_joint1
    - steer_joint2
    - steer_joint3
    - steer_joint4
  gains:
    wheel_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wheel_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wheel_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wheel_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    steer_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    steer_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    steer_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    steer_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1